"""adding created_at updated_at for comments

Revision ID: 9f7cad97537b
Revises: 9a4492b1ea7b
Create Date: 2023-11-05 12:34:38.524129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f7cad97537b'
down_revision: Union[str, None] = '9a4492b1ea7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('text_value', sa.String(), nullable=True))
    op.add_column('comments', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('comments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_comments_text', table_name='comments')
    op.create_index(op.f('ix_comments_text_value'), 'comments', ['text_value'], unique=True)
    op.drop_column('comments', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_comments_text_value'), table_name='comments')
    op.create_index('ix_comments_text', 'comments', ['text'], unique=False)
    op.drop_column('comments', 'updated_at')
    op.drop_column('comments', 'created_at')
    op.drop_column('comments', 'text_value')
    # ### end Alembic commands ###
