"""user limit comments to 1 for each ad

Revision ID: f4f47014d7a9
Revises: 9f7cad97537b
Create Date: 2023-11-05 13:16:01.175647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4f47014d7a9'
down_revision: Union[str, None] = '9f7cad97537b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_ad_user_comment', 'comments', ['ad_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_ad_user_comment', 'comments', type_='unique')
    # ### end Alembic commands ###
